### ISSUE TITLE
Make *.test.ts files work in vscode

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [getsentry/eng-pipes#622]
We exclude the **/*.test.ts files from the src in tsconfig, this means that VS doesn't know about the aliases and therefore shows errors and fails typing.

I'm not sure if there is a good reason to exclude these files (maybe it ensures they are excluded from prod builds?), but I'm also not sure how the tests are running given that they are still typescript.

![image (3)](https://github.com/getsentry/eng-pipes/assets/112419115/deb220a2-6c4e-48b8-8d58-b762a3e9e216)

**Comment by IanWoodard** [comment]
Should be fixed now as of #843
